# Generated by Django 3.1.6 on 2021-09-21 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20210921_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
