# Generated by Django 3.1.6 on 2021-09-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('categories', '0002_auto_20210920_1235'),
        ('modes_of_payment', '0001_initial'),
        ('users', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adulting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_incurred', models.DateField()),
                ('date_posted', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('my_share', models.DecimalField(decimal_places=2, max_digits=32)),
                ('merchandise_total', models.DecimalField(decimal_places=2, max_digits=32)),
                ('merchandise_discount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('shipping_discount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('expected_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_reversal', models.BooleanField(default=False)),
                ('date_reversed', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_category', to='categories.category')),
                ('expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revered_expense', to='expenses.expense')),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_mode_of_payment', to='modes_of_payment.modeofpayment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_destination', to='categories.location')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_expense', to='expenses.expense')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_origin', to='categories.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_mode_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expense', to='expenses.expense')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='share_invoice', to='invoices.invoice')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expense_person', to='persons.person')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineShopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField()),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier', to='categories.courier')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_shopping_expense', to='expenses.expense')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_shopping_platform', to='categories.merchant')),
                ('purchase_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_expense', to='expenses.expense')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_merchant', to='categories.merchant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_transaction_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField()),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='meal_expense', to='expenses.expense')),
                ('order_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_order_mode_category', to='categories.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_merchant', to='categories.merchant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_type_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanCreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adulting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adulting', to='expenses.adulting')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_charge_type', to='categories.category')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to='modes_of_payment.modeofpayment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField()),
                ('online_transaction', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_purchase_courier', to='categories.courier')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_expense', to='expenses.expense')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_merchant', to='categories.merchant')),
                ('purchase_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_purchase_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adulting',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adulting_expense', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='adulting',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adulting_merchant', to='categories.merchant'),
        ),
        migrations.AddField(
            model_name='adulting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adulting_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='adulting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('expense', 'shared_with'), name='unique_shared_expense_person'),
        ),
    ]
