# Generated by Django 3.1.6 on 2021-09-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210921_1447'),
        ('users', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField()),
                ('online_transaction', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pet_purchase_courier', to='categories.courier')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet_expense', to='expenses.expense')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet_merchant', to='categories.merchant')),
                ('purchase_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet_purchase_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
