# Generated by Django 3.1.6 on 2021-08-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reversal',
            name='unique_expense_for_reversal',
        ),
        migrations.AddField(
            model_name='reversal',
            name='date_reversed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reversal',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_for_reversal', to='expenses.expense', unique=True),
        ),
    ]
