# Generated by Django 3.1.6 on 2021-09-21 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210921_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_reversed',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_expense', to='expenses.expense'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(date_posted__gte=django.db.models.expressions.F('date_incurred')), name='incurred_before_posted'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(date_reversed__gte=django.db.models.expressions.F('date_incurred')), name='incurred_before_reversed'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(date_reversed__gte=django.db.models.expressions.F('date_posted')), name='posted_before_reversed'),
        ),
    ]
