# Generated by Django 3.1.6 on 2021-08-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210807_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversal',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_for_reversal', to='expenses.expense'),
        ),
    ]
