# Generated by Django 3.1.6 on 2021-09-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20210912_0853'),
        ('expenses', '0004_auto_20210807_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='share_invoice', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='share',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reversal',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_for_reversal', to='expenses.expense'),
        ),
    ]
