# Generated by Django 3.1.6 on 2021-09-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210921_1752'),
        ('expenses', '0003_auto_20210921_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adulting',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loancreditcard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medical',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineshopping',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
    ]
