# Generated by Django 3.1.6 on 2022-01-29 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20210921_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='merchandise_total',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='my_share',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_expense', to='expenses.expense'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(my_share__lte=django.db.models.expressions.F('total_amount')), name='my_share_lte_to_total_amount'),
        ),
    ]
