# Generated by Django 3.1.6 on 2022-01-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210921_1752'),
        ('categories', '0003_auto_20210921_1752'),
        ('expenses', '0005_auto_20220129_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancreditcard',
            name='adulting',
        ),
        migrations.AddField(
            model_name='loancreditcard',
            name='expense',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='loan_expense', to='expenses.expense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(choices=[(4, 'Meal'), (5, 'Pet'), (6, 'Transportation'), (7, 'Adulting'), (8, 'Loan'), (10, 'Medical'), (11, 'Hobbies'), (12, 'Alignment')], on_delete=django.db.models.deletion.PROTECT, related_name='expense_category', to='categories.category'),
        ),
        migrations.CreateModel(
            name='FriendlyLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_to_pay', models.DateField()),
                ('details', models.TextField(null=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='friendly_loan_expense', to='expenses.expense')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend', to='users.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
