# Generated by Django 3.2.5 on 2021-08-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=16)),
                ('category', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('history', models.JSONField()),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_id', to='categories.category')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
