# Generated by Django 3.1.6 on 2021-09-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20210921_1447'),
        ('users', '0001_initial'),
        ('modes_of_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_incurred', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='modes_of_payment.modeofpayment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='modes_of_payment.modeofpayment')),
                ('transfer_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_channel_category', to='categories.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
