# Generated by Django 3.1.6 on 2021-09-21 17:14

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, source=django.db.models.expressions.F('destination')), name='source_different_from_destination'),
        ),
    ]
