# Generated by Django 3.1.6 on 2021-09-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mode_of_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeofpayment',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='login_url',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='website',
        ),
    ]
